USE ASS;

DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS
 (
   ID INTEGER NOT NULL AUTO_INCREMENT ,
   LOGIN VARCHAR(32) NOT NULL  ,
   MDP VARCHAR(32) NOT NULL  ,
   NOM VARCHAR(64) NULL  ,
   PRENOM VARCHAR(64) NULL  ,
   TYPE VARCHAR(5) NOT NULL DEFAULT 'eleve'
   , PRIMARY KEY (ID)
 )